# Sample .travis.yml for R projects

language: r
r:
  - oldrel
  - release
  - devel
warnings_are_errors: true
sudo: false
cache: packages

r_packages:
  - covr
  - ggplot2
  - dplyr
after_success:
  - Rscript -e 'covr::codecov()'

env:
 global:
   - cran: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    rooms:
      - jaredlander:JmKkasgndHisNTtc39uqw2E8#useful
      - secure: "1pqW4QcYEMLXI6Eh17oHIeLKf3L4rnzwwfIn7WcUMEX/gH5esSPr7jUY50nFqsrnRJCM1g6xQ0ZBougyYtU8ldnNpUNj/X6UgDxjtjCsWi9j/SBV5SvXEcNr0WLXz8NXZg2uUz5zquT6EiVRW/RvKtaKUtwRNluvAUjdkEojuHa8oPWOtxZkQrJJX+WrGBAHQ8dNTaJCeqVCAxfUcxlvNOIP8NR5it11WBaa+ZlMvR505X6ufGdOcBbXWnHH+KDd0WKwcbvX7nApoa/PU7JR/1WEa5m4WyV40521wCsyD+sTro5d74wfX+8SZi+dmjlaRnHf7i1oSoJKfx/E4f0M0gajZ/XFB1jKo2B+iFzuz28L2BZkaDz1xeXysyMyx/F0rGhocPrkek1eBynbNkcn4/C/X+JF8xFHJOaDMFWjVJBxHXQqFGRUcur8TMiSxXbtjjqaetPNq+bEA55bJsSL6+HhFzZL/zkz1S49Do8d2CAAK451sw++ZVbcqVi9oIwPPOMARBWP+cTfz0OkOPB4DDl+uV+THiq8/h/gJ2eGmZwKDu6owXkbpICAKpaIC3OhpANWgOZFMixVfbfLoffKKa7jRKv48RHXHQoQ37pEGTj7MCGkMb7s3L/pi+JSYzbP30731T+VTfjOGz9MGB3I1IjNIKCBaIqigpqlgc9esMA=" # github
      - secure: "Dt8VR6mGvllGODF80U2T6GfyUkphewu4uRVk0WhptaPO4EmZvi27WPa1aCYt4ONqmKdOhLTeYLwimOnqhpSXAJiA8tREOf094bOMRhCrhEUajD32sDYJPzkQ/n3xqOwh7FMO1ydxwATCROHBz2WSHTyAA3t/3lkosokcUbvqPpY2+egSqvxhhn50U34mngJIoNatP91Hpis+aq7xXZ1GzE4wYVSsQyk1b5ITfs3YGaY9+QuvBIOdhUyMMlIeWy4oM52BIrHAmOAIFodeEd0GNcOCH2jp+hJlgyYU8ZhUeQFIJlrVwGeW7fZbPa7o+tdxmOalAflw5hKQ4ufxMp9G2GPM/9Uw8i7TydddFHyx9/alp63g4G5msQDbUrQHbqts2ZpLmN/uVsooaHC1mzwgE81rNfJKTPLsvbIxJlD1qIzifahjhLDJvFbKbzO2tU/+SeHLVMv5zWH0xydZW3Hfs7YREfxF4jDnOuytlQbaTsPjn06zxUW6szpvQ4Zj99IIkvT22TiDIfMWf3D7lr7QmuDFV9/cMkIPoL+XizKIRGcRcWDp+cG3ZFxo5GQNXiykyq624nSpZNIWo7GorBvMbz6e1Pvx8jq+QYAKLTo/FCrxtkICz+zJUVosnML8KrgjDORXB8QHHNJbshXNXzs5wzdTTTkq0v7wdG2CD8NOA7k="  # new
